name: tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  pest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.2', '8.3', '8.4']
        laravel: ['10.*', '11.*', '12.*']
    name: PHP ${{ matrix.php }} / Laravel ${{ matrix.laravel }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, dom, pdo, pdo_mysql, pdo_pgsql
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-update
          composer update --prefer-dist --no-interaction --no-progress

      - name: Run Pest tests
        run: vendor/bin/pest

      - name: Run Pint
        run: vendor/bin/pint --test
